name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  # 🔎 Lint first — must pass or the rest is blocked
  lint:
    name: Ktlint (code style)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Setup Gradle (cache)
        uses: gradle/actions/setup-gradle@v3

      # 👉 Run ktlint and always print violations if it fails, then fail the job
      - name: Run ktlint and print violations
        run: |
          set -o pipefail
          ./gradlew ktlintCheck --console=plain || EXIT_CODE=$?

          # If ktlint failed, try to print human-readable reports, then exit with failure
          if [ -n "${EXIT_CODE}" ]; then
            echo "::group::ktlint reports"
            # Print any PLAIN .txt reports if your Gradle config enables the PLAIN reporter
            found_txt=false
            while IFS= read -r -d '' f; do
              found_txt=true
              echo "===== $f ====="
              cat "$f" || true
              echo
            done < <(find . -type f -path "*/build/reports/ktlint/*/*.txt" -print0)

            # Fallback: if no .txt, dump XML so you still see the violations
            if [ "$found_txt" = false ]; then
              echo "No PLAIN .txt report found; dumping XML instead."
              while IFS= read -r -d '' f; do
                echo "===== $f ====="
                sed -n '1,200p' "$f" || true
                echo
              done < <(find . -type f -path "*/build/reports/ktlint/*/*.xml" -print0)
              echo "Tip: enable PLAIN reporter in Gradle for nicer console output."
            fi
            echo "::endgroup::"
            exit 1
          fi

  # 🧱 Build only runs if lint passed
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
